import { Event, ConstraintTrace } from './types';
import { ConstraintParams } from './params';

/**
 * Construye el ConstraintTrace explicativo (§15.3 y §18) comparando la agenda
 * original del usuario contra la propuesta optimizada por el solver.
 */
export function buildConstraintTrace(
  originalSchedule: Event[],
  optimizedSchedule: Event[],
  params: ConstraintParams,
  scoreDelta: number
): ConstraintTrace[] {
  const traces: ConstraintTrace[] = [];
  const originalMap = new Map(originalSchedule.map(e => [e.id, e]));

  for (const opt of optimizedSchedule) {
    const orig = originalMap.get(opt.id);

    if (!orig) {
      // Evento auto-insertado (ej. buffer de traslado, slot de serendipia)
      traces.push({
        eventId: opt.id,
        changeType: 'auto_inserted',
        primaryTrigger: {
          constraintId: opt.autoGeneratedReason?.includes('HC-05') ? 'HC-05' : 'SC-15',
          constraintName: opt.name,
          explanation: opt.autoGeneratedReason ?? 'Generado automáticamente por optimización de agenda.',
          severity: opt.autoGeneratedReason?.includes('HC') ? 'hard' : 'soft',
        },
        scoreImpact: 0,
        newSlot: {
          start: new Date(opt.start),
          end: new Date(new Date(opt.start).getTime() + opt.duration * 60 * 1000),
        },
      });
      continue;
    }

    const origTime = new Date(orig.start).getTime();
    const optTime = new Date(opt.start).getTime();
    const isMoved = origTime !== optTime;
    const isResized = orig.duration !== opt.duration;
    const isRelocated = orig.location.type !== opt.location.type;

    if (isMoved || isResized || isRelocated) {
      // Determinar disparador primario
      let constraintId = 'SC-01';
      let constraintName = 'Optimización general';
      let explanation = `Reubicado para mejorar la fluidez y descanso semanal.`;
      let severity: 'hard' | 'graduated' | 'soft' = 'soft';

      if (isRelocated) {
        constraintId = 'HC-08';
        constraintName = 'Reubicación por clima';
        explanation = `Reubicado a ${opt.location.name} debido a clima extremo adverso.`;
        severity = 'hard';
      } else if (opt.cannabis_consumed) {
        constraintId = 'GHC-01';
        constraintName = 'Buffer post-consumo';
        explanation = `Buffer adaptado para coordinar compromisos respetando el piso de seguridad.`;
        severity = 'graduated';
      } else if (opt.category === 'estudio') {
        constraintId = 'SC-01';
        constraintName = 'Bloques de estudio';
        explanation = `Alineado para garantizar concentración continua de al menos ${params.study_block_min_duration} min.`;
        severity = 'soft';
      }

      traces.push({
        eventId: opt.id,
        changeType: isRelocated ? 'relocated' : (isMoved ? 'moved' : 'resized'),
        primaryTrigger: {
          constraintId,
          constraintName,
          explanation,
          severity,
        },
        scoreImpact: Math.round(scoreDelta / 3),
        previousSlot: {
          start: new Date(orig.start),
          end: new Date(origTime + orig.duration * 60 * 1000),
        },
        newSlot: {
          start: new Date(opt.start),
          end: new Date(optTime + opt.duration * 60 * 1000),
        },
      });
    }
  }

  return traces;
}
