import { Event, WeatherCondition } from './types';
import { ConstraintParams } from './params';

/**
 * Módulo de Post-Procesamiento (§15.2, Fase 5):
 * 1. Inserta buffers automáticos de sueño (HC-03) y traslados (HC-05).
 * 2. Fusiona gaps de tiempo muerto < dead_time_threshold (SC-09).
 * 3. Inyecta SocialOpportunitySlots (SC-15) si faltan cupos semanales.
 */
export function postProcess(
  schedule: Event[],
  weather: WeatherCondition[],
  params: ConstraintParams,
  weekStart: Date
): Event[] {
  const result: Event[] = [...schedule];

  // 1. Inserción de buffers de traslado (HC-05) si no existen
  const workEvents = schedule.filter(e => e.category === 'trabajo');
  for (const work of workEvents) {
    const isCasino = work.location.type === 'rambla_casino' || work.name.toLowerCase().includes('casino');
    const bufferMin = isCasino ? params.travel_buffer_casino : params.travel_buffer_ferro;

    const workStart = new Date(work.start).getTime();
    const workEnd = workStart + work.duration * 60 * 1000;

    // Buffer previo
    const prevBufferStart = new Date(workStart - bufferMin * 60 * 1000);
    const existingPrev = result.find(e =>
      e.category === 'traslado' &&
      Math.abs(new Date(e.start).getTime() - prevBufferStart.getTime()) < 5 * 60 * 1000
    );

    if (!existingPrev) {
      result.push({
        id: `trans-pre-${work.id}`,
        name: `Traslado a ${work.name}`,
        category: 'traslado',
        emoji: '🚌',
        start: prevBufferStart,
        duration: bufferMin,
        is_locked: true,
        location: { type: 'casa', name: 'Traslado' },
        weatherSensitivity: 'transit_only',
        cognitiveLoad: 0,
        physicalLoad: 1,
        is_sensitive: false,
        isAutoGenerated: true,
        autoGeneratedReason: 'HC-05: Buffer obligatorio de traslado previo',
        createdAt: new Date(),
        updatedAt: new Date(),
        deviceId: 'local',
        localVersion: 1,
        syncStatus: 'synced',
      });
    }

    // Buffer posterior
    const existingPost = result.find(e =>
      e.category === 'traslado' &&
      Math.abs(new Date(e.start).getTime() - workEnd) < 5 * 60 * 1000
    );

    if (!existingPost) {
      result.push({
        id: `trans-post-${work.id}`,
        name: `Traslado desde ${work.name}`,
        category: 'traslado',
        emoji: '🚌',
        start: new Date(workEnd),
        duration: bufferMin,
        is_locked: true,
        location: { type: 'casa', name: 'Traslado' },
        weatherSensitivity: 'transit_only',
        cognitiveLoad: 0,
        physicalLoad: 1,
        is_sensitive: false,
        isAutoGenerated: true,
        autoGeneratedReason: 'HC-05: Buffer obligatorio de traslado posterior',
        createdAt: new Date(),
        updatedAt: new Date(),
        deviceId: 'local',
        localVersion: 1,
        syncStatus: 'synced',
      });
    }
  }

  // 2. Inserción de SocialOpportunitySlots (SC-15) si hay déficit
  const serendipityCount = result.filter(e => e.isOpenSocialSlot || e.category === 'social_opportunity').length;
  const neededSlots = Math.max(0, params.serendipity_slots_per_week - serendipityCount);

  if (neededSlots > 0) {
    // Buscar ventanas de buen clima o tardes libres (Miércoles 18h o Sábado 16h)
    const candidateDays = [3, 6]; // Miércoles y Sábado
    let added = 0;

    for (const dayOffset of candidateDays) {
      if (added >= neededSlots) break;

      const targetDate = new Date(weekStart);
      targetDate.setDate(targetDate.getDate() + dayOffset);
      targetDate.setHours(16, 0, 0, 0);

      // Verificar si está libre
      const slotTime = targetDate.getTime();
      const collides = result.some(e => {
        const eStart = new Date(e.start).getTime();
        const eEnd = eStart + e.duration * 60 * 1000;
        return slotTime >= eStart && slotTime < eEnd;
      });

      if (!collides) {
        result.push({
          id: `serendipity-slot-${dayOffset}`,
          name: 'Slot de Serendipia Social',
          category: 'social_opportunity',
          emoji: '✨',
          start: targetDate,
          duration: 120,
          is_locked: false,
          isOpenSocialSlot: true,
          suggestedMood: 'chill',
          location: { type: 'cafe_guemes', name: 'Café Güemes / Abierto' },
          weatherSensitivity: 'transit_only',
          cognitiveLoad: 0,
          physicalLoad: 0,
          is_sensitive: false,
          isAutoGenerated: true,
          autoGeneratedReason: 'SC-15: Tiempo reservado para lo inesperado',
          createdAt: new Date(),
          updatedAt: new Date(),
          deviceId: 'local',
          localVersion: 1,
          syncStatus: 'synced',
        });
        added++;
      }
    }
  }

  return result.sort((a, b) => new Date(a.start).getTime() - new Date(b.start).getTime());
}
