import { Contact, Event, Location, LocationType, WeatherCondition } from './types';

export const INTIMATE_HOME_ALLOWED_CONTACT_NAMES = ['Juani', 'Juancito'];

/**
 * Validates whether a contact is permitted to visit Matu's family home.
 * Enforces strict family home privacy constraints (§11.4):
 * - Home is ONLY accessible to intimate inner circle (Juani, Juancito).
 * - Home is NEVER accessible to casual acquaintances, new contacts, or delicate connections.
 */
export function canHostAtHome(contact?: Contact): boolean {
  if (!contact) return false;
  if (contact.relationshipType !== 'amigo_cercano') return false;
  return INTIMATE_HOME_ALLOWED_CONTACT_NAMES.some(
    (allowed) =>
      contact.name.toLowerCase().includes(allowed.toLowerCase()) ||
      (contact.alias && contact.alias.toLowerCase().includes(allowed.toLowerCase()))
  );
}

/**
 * Suggests a social meeting location according to weather and contact layer.
 * Rule: Home is NEVER proposed as a general fallback for Layer B or casual contacts.
 */
export function suggestSocialLocation(
  contact?: Contact,
  weatherCondition?: WeatherCondition
): Location {
  const comfort = weatherCondition?.comfortScore ?? 60;

  // Good weather: outdoor opportunities (§12.4 Regla 2)
  if (comfort >= 70) {
    return {
      type: 'exterior_rambla',
      name: 'Rambla Casino / Playa Bristol',
    };
  }

  // Mediocre or bad weather: Indoor fallback
  // Priority 1: Contact's private apartment if available
  if (contact?.hasPrivateApartment) {
    return {
      type: 'depto_contacto',
      name: `Depto de ${contact.alias || contact.name}`,
    };
  }

  // Priority 2: Café Güemes
  if (comfort >= 40) {
    return {
      type: 'cafe_guemes',
      name: 'Café de calle Güemes',
      address: 'Zona Güemes, Mar del Plata',
    };
  }

  // Priority 3: Paseo Aldrey (full shelter from coastal rain/wind)
  return {
    type: 'paseo_aldrey',
    name: 'Paseo Aldrey Shopping',
    address: 'Sarmiento 2685, Mar del Plata',
  };
}

/**
 * Identifies and generates Layer C serendipity / social opportunity slots (§11.1).
 */
export function generateSerendipitySlots(
  existingEvents: Event[],
  weatherConditions: WeatherCondition[],
  countTarget: number = 2,
  weekStartDate: Date = new Date()
): Event[] {
  const slots: Event[] = [];
  const start = new Date(weekStartDate);
  start.setHours(0, 0, 0, 0);

  // Preferred serendipity hours: Friday, Saturday, Sunday afternoons (17:00 - 21:00)
  const candidateDays = [5, 6, 0]; // Fri, Sat, Sun

  for (const dayOffset of [5, 6, 0, 4, 3]) {
    if (slots.length >= countTarget) break;

    const candidateDate = new Date(start);
    candidateDate.setDate(candidateDate.getDate() + dayOffset);
    candidateDate.setHours(18, 0, 0, 0);
    const duration = 90; // 90 minutes
    const end = new Date(candidateDate.getTime() + duration * 60000);

    // Check collision with existing events
    const hasCollision = existingEvents.some((e) => {
      const eStart = new Date(e.start).getTime();
      const eEnd = eStart + e.duration * 60000;
      return candidateDate.getTime() < eEnd && end.getTime() > eStart;
    });

    if (!hasCollision) {
      // Find weather for this slot
      const weather = weatherConditions.find(
        (w) => Math.abs(new Date(w.timestamp).getTime() - candidateDate.getTime()) < 3600000
      );

      const loc = suggestSocialLocation(undefined, weather);

      slots.push({
        id: `serendipity_slot_${dayOffset}_${candidateDate.toISOString().slice(0, 10)}`,
        name: 'Slot de Serendipia Social',
        emoji: '✨',
        category: 'social_opportunity',
        start: candidateDate,
        duration,
        is_locked: false,
        isOpenSocialSlot: true,
        location: loc,
        weatherSensitivity: 'outdoor_full',
        cognitiveLoad: 0,
        physicalLoad: 0,
        is_sensitive: false,
        isAutoGenerated: true,
        autoGeneratedReason: 'SC-15: Ventana abierta para serendipia y nuevas conexiones',
        createdAt: new Date(),
        updatedAt: new Date(),
        deviceId: 'local',
        localVersion: 1,
        syncStatus: 'synced',
      });
    }
  }

  return slots;
}
