export type DayOfWeek = 0 | 1 | 2 | 3 | 4 | 5 | 6; // 0 = Domingo

export type LocationType =
  | 'casa'
  | 'rambla_casino'
  | 'ferro_san_juan'
  | 'facultad'
  | 'exterior_rambla'
  | 'exterior_plaza'
  | 'cafe_guemes'
  | 'paseo_aldrey'
  | 'gym'
  | 'depto_contacto'
  | 'custom';

export interface Location {
  type: LocationType;
  name: string;
  address?: string;
  lat?: number;
  lon?: number;
}

export type EventCategory =
  | 'trabajo'
  | 'cursada'
  | 'estudio'
  | 'social'
  | 'gym'
  | 'batch_cooking'
  | 'comida'
  | 'sueno'
  | 'traslado'
  | 'tramites'
  | 'desarrollo_personal'
  | 'recuperacion'
  | 'buffer_post_consumo'
  | 'social_opportunity'
  | 'preparacion_buffer'
  | 'otro';

export type WeatherSensitivity = 'none' | 'transit_only' | 'outdoor_full';

export interface EventDependency {
  targetEventId: string;
  type: 'after' | 'same_day' | 'requires_completed';
  minGapMinutes?: number;
  maxGapMinutes?: number;
}

export interface Event {
  id: string;
  name: string;
  category: EventCategory;
  emoji?: string;

  // Tiempo
  start: Date;              // UTC interno; representación en ART (UTC-3)
  duration: number;         // Minutos, siempre múltiplos de 15
  is_locked: boolean;       // Controlado por toggle UI explícito

  // Recurrencia
  recurrenceId?: string;
  isRecurrenceException?: boolean;
  exceptionFor?: Date;

  // Ubicación y clima
  location: Location;
  weatherSensitivity: WeatherSensitivity;

  // Social
  contacts?: string[];
  isOpenSocialSlot?: boolean;
  suggestedMood?: 'energetic' | 'chill' | 'any';

  // Carga energética
  cognitiveLoad: 0 | 1 | 2 | 3;
  physicalLoad: 0 | 1 | 2 | 3;

  // Economía
  estimatedCostARS?: number;
  costCategory?: 'free' | 'cheap' | 'moderate' | 'expensive';

  // Privacidad / Local-only
  is_sensitive: boolean;
  cannabis_consumed?: boolean;   // Activa GHC-01
  displayAlias?: string;         // Alias público para iCal / sync
  notesEncrypted?: string;

  // Flags de post-procesamiento del solver
  isAutoGenerated?: boolean;
  autoGeneratedReason?: string;
  isRecoverySlot?: boolean;
  isPreparationBuffer?: boolean;

  // Dependencias
  dependsOn?: EventDependency[];

  // Sync
  createdAt: Date;
  updatedAt: Date;
  deviceId: string;
  localVersion: number;
  syncStatus: 'synced' | 'pending' | 'conflict';
}

export type RecurrenceFrequency = 'daily' | 'weekly' | 'biweekly' | 'monthly';

export interface RecurrenceException {
  date: Date;
  type: 'skip' | 'reschedule' | 'modify';
  override?: Partial<Event>;
  note?: string;
}

export interface RecurrencePattern {
  id: string;
  frequency: RecurrenceFrequency;
  daysOfWeek?: DayOfWeek[];
  startDate: Date;
  until?: Date;
  occurrenceCount?: number;
  exceptions: RecurrenceException[];
}

export type CardinalDirection = 'N' | 'NE' | 'E' | 'SE' | 'S' | 'SW' | 'W' | 'NW';

export interface WeatherCondition {
  timestamp: Date;
  precipitationProbability: number;   // 0.0 – 1.0
  precipitationMm: number;
  windSpeedKmh: number;
  windDirection: CardinalDirection;
  temperatureCelsius: number;
  feelsLikeCelsius: number;
  comfortScore: number;               // 0 – 100 computado
}

export interface Contact {
  id: string;
  name: string;
  alias?: string;
  relationshipType: 'amigo_cercano' | 'facultad' | 'trabajo' | 'conocido' | 'vinculo_delicado';
  weeklyHoursGoal?: number;           // Para SC-03
  busySlots?: { dayOfWeek: DayOfWeek; start: string; end: string }[];
  hasPrivateApartment?: boolean;      // Para HC-08 fallback
  isSensitive?: boolean;              // Para SC-16 (Lau)
  notes?: string;
}

export interface TimeSlot {
  start: Date;
  end: Date;
}

export interface ConstraintTrace {
  eventId: string;
  changeType: 'moved' | 'resized' | 'relocated' | 'auto_inserted' | 'removed';
  primaryTrigger: {
    constraintId: string;     // "GHC-01", "SC-08", "HC-03", etc.
    constraintName: string;
    explanation: string;      // En lenguaje natural
    severity: 'hard' | 'graduated' | 'soft';
  };
  secondaryTriggers?: { constraintId: string; explanation: string }[];
  scoreImpact: number;
  previousSlot?: TimeSlot;
  newSlot?: TimeSlot;
  ghcViolationAmount?: number; // Minutos faltantes para el target si es GHC
  alternativesConsidered?: { slot: TimeSlot; scoreIfChosen: number; whyRejected: string }[];
}

export type HardConstraintId =
  | 'HC-01'
  | 'HC-02'
  | 'HC-03'
  | 'HC-05'
  | 'HC-05b'
  | 'HC-07'
  | 'HC-08'
  | 'HC-09'
  | 'HC-10'
  | 'HC-11';

export type GHCId = 'GHC-01';

export type SoftConstraintId =
  | 'SC-01'
  | 'SC-02'
  | 'SC-03'
  | 'SC-04'
  | 'SC-05'
  | 'SC-06'
  | 'SC-07'
  | 'SC-08'
  | 'SC-08b'
  | 'SC-09'
  | 'SC-10'
  | 'SC-11'
  | 'SC-12'
  | 'SC-13'
  | 'SC-14'
  | 'SC-15'
  | 'SC-16';

export interface HardConstraintConfig {
  id: HardConstraintId;
  name: string;
  enabled: boolean;
  isConfigurable: boolean;
}

export interface GHCConfig {
  id: GHCId;
  name: string;
  weight: number;
  target: number;
  floor: number;
}

export interface SoftConstraintConfig {
  id: SoftConstraintId;
  name: string;
  weight: number;
  enabled: boolean;
}

export interface WeeklyConstraintOverride {
  constraintId: SoftConstraintId | GHCId;
  weekNumber: number;
  year: number;
  overrideWeight?: number;
  disabled?: boolean;
}

export interface ActivityWeatherProfile {
  category: EventCategory;
  minComfortScore: number;
  toleratesRainTransit: boolean;
  fallbackIndoorLocation?: LocationType;
}

export interface PersonalGoal {
  id: string;
  title: string;
  category: EventCategory;
  targetHoursPerWeek: number;
}

export interface MiMesaConfig {
  userId: string;
  deviceId: string;

  // Restricciones y pesos
  hardConstraints: Record<HardConstraintId, HardConstraintConfig>;
  graduatedHardConstraints: Record<GHCId, GHCConfig>;
  softConstraints: Record<SoftConstraintId, SoftConstraintConfig>;
  weeklyOverrides: WeeklyConstraintOverride[];

  // Parámetros numéricos editables (Principio P9)
  params: import('./params').ConstraintParams;

  // Meta-sliders (0–10)
  metaSliders: {
    depthVsAmplitudeSocial: number;   // 0=sostener lo que tengo, 10=conocer gente nueva
    productivityVsEnjoyment: number;  // 0=enfocado en estudio, 10=modo social
    introvertVsExtrovert: number;     // 0=encontrarme a mí mismo, 10=con gente
  };

  // Contactos
  contacts: Contact[];

  // Clima
  weatherLocation: { lat: number; lon: number };
  activityWeatherProfiles: ActivityWeatherProfile[];

  // Preferencias horarias
  energyPeakHours: { start: string; end: string };
  preferredStudyHours: { start: string; end: string };

  // Economía
  weeklyBudgetARS?: number;
  personalGoals: PersonalGoal[];

  // Planificación
  weeklyPlanningDay: DayOfWeek;
  weeklyPlanningTime: string;
  dailyMicroAdjustTime: string;

  // Sync
  syncEnabled: boolean;
  supabaseUserId?: string;
  localOnlyFields: string[];

  // Aprendizaje
  patternLearningEnabled: boolean;
}

export interface SolverInput {
  schedule: Event[];
  weather: WeatherCondition[];
  params: import('./params').ConstraintParams;
  weights: Record<string, number>;
  contacts: Contact[];
}

export interface SolverResult {
  feasible: boolean;
  violations?: string[];
  schedule: Event[];
  score: number;
  scoreBreakdown: {
    hardViolationsCount: number;
    ghcPenalties: Record<string, number>;
    softPenalties: Record<string, number>;
  };
  constraintTrace: ConstraintTrace[];
  solvingTimeMs: number;
}
